fixtures:
  symlinks:
    base: '#{source_dir}'
  repositories:
    talend: 'git@github.com:lucadevitis-msm/puppet-talend'
  forge_modules:
    stdlib:
      repo: 'puppetlabs/stdlib'
      ref: '4.6.0'
    archive:
      repo: 'puppet/archive'
      ref: '1.0.0'
